name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build backend image
      - name: Build backend image
        run: |
          docker build -t backend-test ./backend

      # Step 4: Build frontend image
      - name: Build frontend image
        run: |
          docker build -t frontend-test ./frontend
